export const reduxConstants = {
    ADD_CATEGORY: 'ADD_CATEGORY',
    DELETE_CATEGORY: 'DELETE_CATEGORY',
    ADD_ATTRIBUTE_TO_CATEGORY: 'ADD_ATTRIBUTE_TO_CATEGORY',
    CATEGORY_ATTRIBUTE_CHANGE: 'CATEGORY_ATTRIBUTE_CHANGE',
    UPDATE_CAGEGORY_TITLE_FIELD: 'UPDATE_CAGEGORY_TITLE_FIELD',
    UPDATE_CAGEGORY_NAME: 'UPDATE_CAGEGORY_NAME',


    ADD_CATEGORY_ITEM: 'ADD_CATEGORY_ITEM',
    UDPATE_CATEGORY_ITEM: 'UDPATE_CATEGORY_ITEM',
    DELETE_CATEGORY_ITEM: 'DELETE_CATEGORY_ITEM',
  };
  